services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            network: host
        ports:
            - "0.0.0.0:4567:8080"
        environment:
            #- APP_KEY=
            - PHP_OPCACHE_ENABLE=1
            - TRMNL_PROXY_REFRESH_MINUTES=15
            - DB_DATABASE=database/storage/database.sqlite
        volumes:
           - database:/var/www/html/database/storage
           - storage:/var/www/html/storage/app/public/images/generated
        restart: unless-stopped
        #platform: "linux/arm64/v8"
    tunnel:
      image: cloudflare/cloudflared:latest
      container_name: cloudflared
      command: tunnel --no-autoupdate run
      environment:
        - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      restart: unless-stopped
      networks:
        - cloudflared-network
networks:
    cloudflared-network:
      driver: bridge
volumes:
    database:
    storage:

